/**
 * @file Debug.cpp
 * @brief UART5 LL backend for the Debug logging library.
 *
 * Physical layer: UART5, PC12 TX / PD2 RX, 115200 baud (async mode).
 * The peripheral is initialised by MX_UART5_Init() in CubeMX-generated code
 * before this library is used.
 *
 * _write syscall is overridden here (strong symbol) so that printf() and any
 * other newlib I/O function routes through UART5 automatically.
 */

#include "Debug.h"

#include <cstdio>
#include <cstdarg>

// LL peripheral header — generated by CubeMX
#include "stm32g4xx_ll_usart.h"


static Level s_level = Level::LOG_DEBUG;  //< Active verbosity level

static const char *level_prefix(Level level)
{
    switch (level) {
        case Level::LOG_DEBUG: return "[DBG] ";
        case Level::LOG_INFO:  return "[INF] ";
        case Level::LOG_WARN:  return "[WRN] ";
        default:               return "";
    }
}

void SerialDebug::putchar(char ch)
{
    // Wait until TXE (transmit data register empty)
    while (!LL_USART_IsActiveFlag_TXE(UART5)) {}
    LL_USART_TransmitData8(UART5, static_cast<uint8_t>(ch));
}

void SerialDebug::setLevel(Level lvl)
{
    s_level = lvl;
}

void SerialDebug::vlog(Level lvl, const char *fmt, va_list args)
{
    if (s_level == Level::LOG_OFF || lvl > s_level) {
        return;
    }

    // Print level prefix
    const char *prefix = level_prefix(lvl);
    while (*prefix) {
        Debug.putchar(*prefix++);
    }

    // Format the message into a local buffer to avoid repeated putchar calls
    char buf[128];
    int n = vsnprintf(buf, sizeof(buf), fmt, args);

    // Transmit the formatted string; clamp to buffer size on overflow
    int send = (n > 0 && n < (int)sizeof(buf)) ? n : (int)sizeof(buf) - 1;
    for (int i = 0; i < send; ++i) {
        Debug.putchar(buf[i]);
    }
}

void SerialDebug::log(Level lvl, const char *fmt, ...)
{
    va_list args;
    va_start(args, fmt);
    vlog(lvl, fmt, args);
    va_end(args);
}

// _write syscall retarget — strong override of the CubeMX weak stub.
extern "C" int _write(int file, char *ptr, int len)
{
    (void)file;
    for (int i = 0; i < len; ++i) {
        Debug.putchar(ptr[i]);
    }
    return len;
}

// Creation of the default instance
SerialDebug Debug;
